package com.orbekk.stats;

import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import com.google.protobuf.RpcCallback;
import com.google.protobuf.RpcController;
import com.orbekk.stats.Experiments.Empty;
import com.orbekk.stats.Experiments.Experiment1;
import com.orbekk.stats.Experiments.SimpleTiming;

public class Experiment1Impl extends Experiment1 {
    private final static Logger logger = Logger.getLogger(Experiment1Impl.class.getName());
    private List<SimpleTiming> samples = new ArrayList<SimpleTiming>();
    
    @Override
    public synchronized void registerSample(RpcController controller, SimpleTiming request,
            RpcCallback<Empty> done) {
        logger.info(request.toString());
        samples.add(request);
        done.run(Empty.getDefaultInstance());
    }
    
    public void writeSamples(String filename) {
        PrintWriter printer = null;
        try {
            printer = new PrintWriter(filename);
            System.out.println("Writing results to " + filename);
            printer.println("# Automatically generated by Experiment1Impl.java");
            for (SimpleTiming timing : samples) {
                printer.println(timing);
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } finally {
            if (printer != null) {
                printer.close();
            }
        }
    }
}
